name: 'Version Bump'
description: 'Calculate semantic version bump based on conventional commits'

inputs:
  force_bump:
    description: 'Override automatic detection (patch, minor, major, or empty)'
    required: false
    default: ''

outputs:
  bump-type:
    description: 'Calculated bump type'
    value: ${{ steps.calculate.outputs.bump-type }}
  current-version:
    description: 'Version from Cargo.toml'
    value: ${{ steps.calculate.outputs.current-version }}
  new-version:
    description: 'Next version number'
    value: ${{ steps.calculate.outputs.new-version }}
  new-tag:
    description: 'Tag name (e.g., v1.2.3)'
    value: ${{ steps.calculate.outputs.new-tag }}

runs:
  using: 'composite'
  steps:
    - name: Calculate version bump
      id: calculate
      shell: bash
      run: |
        # Read current version from Cargo.toml
        CURRENT_VERSION=$(grep -m1 '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
        echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

        # Parse version components
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

        # Get commits since last tag (or all commits if no tag)
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        if [ -n "$LAST_TAG" ]; then
          COMMITS=$(git log "$LAST_TAG"..HEAD --pretty=format:"%s")
        else
          COMMITS=$(git log --pretty=format:"%s")
        fi

        # Determine bump type
        BUMP_TYPE="patch"

        if [ -n "${{ inputs.force_bump }}" ]; then
          BUMP_TYPE="${{ inputs.force_bump }}"
        else
          # Check for breaking changes (!)
          if echo "$COMMITS" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|deps|security|release)!"; then
            BUMP_TYPE="major"
          # Check for new features
          elif echo "$COMMITS" | grep -qE "^feat(\(.+\))?:"; then
            BUMP_TYPE="minor"
          # Check for patch-worthy commits
          elif echo "$COMMITS" | grep -qE "^(fix|perf|refactor|revert|security|deps|release)(\(.+\))?:"; then
            BUMP_TYPE="patch"
          fi
        fi

        echo "bump-type=$BUMP_TYPE" >> $GITHUB_OUTPUT

        # Calculate new version
        case "$BUMP_TYPE" in
          major)
            NEW_VERSION="$((MAJOR + 1)).0.0"
            ;;
          minor)
            NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
            ;;
          patch)
            NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
            ;;
        esac

        echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "new-tag=v$NEW_VERSION" >> $GITHUB_OUTPUT

        # Check if tag already exists
        if git rev-parse "v$NEW_VERSION" >/dev/null 2>&1; then
          echo "Error: Tag v$NEW_VERSION already exists"
          exit 1
        fi

        echo "Version bump: $CURRENT_VERSION -> $NEW_VERSION ($BUMP_TYPE)"
